### ISSUE TITLE
es6/7 import syntax stacks the imports

### ISSUE THREAD

**Issue by nCubed** [Lonefy/vscode-JS-CSS-HTML-formatter#10]
When using es6/7 imports, the objects to import are reformatted to something along the lines of json/js syntax.

Example:
```javascript
import { foo } from 'foo-framework';
```

Becomes:
```javascript
import {
    foo
} from 'foo-framework';
```

Is there a way to keep the imports either unmodified or keep them on a single line?

**Comment by Lonefy** [comment]
Duplicate of #9 , thanks for the report :)
