### ISSUE TITLE
Format scss files too

### ISSUE THREAD

**Issue by Arrow7000** [Lonefy/vscode-JS-CSS-HTML-formatter#14]
Firstly great extension! I use it the entire time!

It would be great if this could format Sass files (.scss extension) too. The shortcut is basically a muscle memory twitch now and it feels strange to see it do nothing to badly formatted Sass files.

Thanks!

**Comment by Arrow7000** [comment]
Just submitted a pull request for it: #15

**Comment by Lonefy** [comment]
Published v0.2.0, thanks for the commit~ :)
