### ISSUE TITLE
Format Code - set indent

### ISSUE THREAD

**Issue by tonytmtsh** [Lonefy/vscode-JS-CSS-HTML-formatter#2]
Currently this sets the indent at 4 characters.  Can I change that to be 3 characters?

**Comment by Lonefy** [comment]
@tonytmtsh Thx for the suggestion, I've added the config feature. U can use the command `Formatter Config` to set the options. For more info [Readme](https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/blob/master/README.md);
