### ISSUE TITLE
Config file in project folder

### ISSUE THREAD

**Issue by aaweb** [Lonefy/vscode-JS-CSS-HTML-formatter#3]
Hey there

Thanks for the great plugin. Is is possible to have a config.json located inside a VS Code project? For example, inside the .vscode folder.

I would like to have the config in our repo and share it with the team.

Thanks
Andy

**Comment by rjmacarthy** [comment]
Have created pull request suggestion to resolve this issue.

**Comment by Lonefy** [comment]
Done! Thanks for the suggestion!
