### ISSUE TITLE
Adopt formatOnSave changes

### ISSUE THREAD

**Issue by jrieken** [Lonefy/vscode-JS-CSS-HTML-formatter#30]
Since VS Code now has the `editor.formatOnSave`-setting and the `onWillSaveTextDocument`-event, [this code](https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/blob/master/src/extension.ts#L117) should be revisited. I'd recommend to remove it and to rely on the built-in `formatOnSave` feature or to use the new event. Both will prevent unnecessary fs-operations and reduce the risk for endless write-event-write loops. 

See https://code.visualstudio.com/updates#_format-on-save, Microsoft/vscode#12449, and Microsoft/vscode#239 for more details

**Comment by Lonefy** [comment]
Done

**Comment by jrieken** [comment]
Thanks
