### ISSUE TITLE
Format on Save

### ISSUE THREAD

**Issue by jchannon** [Lonefy/vscode-JS-CSS-HTML-formatter#4]
Is there an option in this plugin or js-beautify to format on save?

**Comment by Lonefy** [comment]
@jchannon Sorry, currently not. I'll try to add this feature soon. Thx for this suggestion :)

**Comment by Lonefy** [comment]
@jchannon `onSave` feature has been added

**Comment by nuqz** [comment]
@Lonefy every time when I save file cursor goes to the end of formatted file. I want to remember my cursor position after formatting. Is it possible?

**Comment by Kailash23** [comment]
@nuqz @Lonefy Same problem. Please fixed this issue cursor goes to the end line after saving.

**Comment by bmarkovic** [comment]
The extension doesn't respect the `onSave` option being set to `false` (not the mention audacity of assuming setting it to `true` is a default anyone would want or expect). It constantly formatted my files on save. I had to uninstall.

**Comment by subhnet** [comment]
Is there an option to disable the onSave option?

**Comment by hazho** [comment]
fuck all of you who made this fucking ball of shit, you destroyed my entire project of months working on...!

**Comment by hazho** [comment]
you destroyed my entire project of months working on...!

please warn the new installers about auto formatting on file save

**Comment by Srikara369** [comment]
in VS Code, Press F1 -> Search for "Formatter Config" and open it.
Change 'onSave' to false. Restart VS Code.
Enjoy :)
