### ISSUE TITLE
Add an example of config for formatting minified JS

### ISSUE THREAD

**Issue by BairDev** [Lonefy/vscode-JS-CSS-HTML-formatter#5]
It is really hard to figure out, how to make a minified JS file human readable. *Minified* means here, that all white space has been removed and the lines do not end with signs like *;,{*.

At least, I was not able to beautify a JS file, which has been created by the TypeScript compiler. Its options were set to:

```(json)
"compilerOptions": {
  "target": "es5",
  "module": "commonjs",
  "declaration": false,
  "noImplicitAny": false,
  "removeComments": true,
  "noLib": false,
  "preserveConstEnums": true,
  "suppressImplicitAnyIndexErrors": true,
  "outDir": "./tmp/typescript",
  "rootDir": "./src/app.ts"
}
```

**Comment by Lonefy** [comment]
@BairDev Does the `F1->Formatter`  work?
![image](https://cloud.githubusercontent.com/assets/7921431/15003648/896189a2-11e0-11e6-8dc4-3230fe52a4ec.png)

**Comment by BairDev** [comment]
Umm, yes, this works. Aright, thanks for helping a clueless person out.
