### ISSUE TITLE
A problem caused by the extension.

### ISSUE THREAD

**Issue by blusoul** [Lonefy/vscode-JS-CSS-HTML-formatter#51]
Excuse me .
I installed this extension , the global replacement function is affected
More info.[Search-and-replace in more than one file](https://github.com/Microsoft/vscode/issues/21269)

**Comment by blusoul** [comment]
Thanks, I have uninstalled.

**Comment by jesobreira** [comment]
I think this should be re-opened and taken into consideration, @Lonefy
