### ISSUE TITLE
File corrupted while saving after close all #21993

### ISSUE THREAD

**Issue by zhoudxnz** [Lonefy/vscode-JS-CSS-HTML-formatter#53]
With onSave = true, 
When I have multiple modified javascript files open in the editor, I click 'Close All' and then click Save when prompted, one of my file would get corrupted.    
https://github.com/Microsoft/vscode/issues/21993

**Comment by lainz** [comment]
Hi also it happens when you click Save All
Microsoft/vscode/issues/#22330

**Comment by jrieken** [comment]
@Lonefy This is showing up quite often in VS Code. The `onWillSave` logic doesn't create edits for the  saving document but for the active editor which is the cause of this. Let me know if want a PR for this.

**Comment by jrieken** [comment]
Thanks! Please also publish a new version of your extensions so that everyone gets this fix

**Comment by Lonefy** [comment]
@jrieken Sorry for my late feedback, cause I'm too busy this few months. And since my old `vsce PAT`  expaired ,I'm having some problem with `publish`

**Comment by Lonefy** [comment]
@jrieken Sorry for my late feedback.I'm really busy these few months.And really thanks for this merge. I've published the new version.

**Comment by jrieken** [comment]
Thanks and happy coding!
