### ISSUE TITLE
Can't support React jsx code

### ISSUE THREAD

**Issue by Hancoson** [Lonefy/vscode-JS-CSS-HTML-formatter#64]
Can't support React jsx code.
The normal code like this:
![qq 20170426105330](https://cloud.githubusercontent.com/assets/5474666/25416139/c782107e-2a6e-11e7-88c8-4492486df89c.png)
But I use `Alt+Shift+F` to beautify the code like this:
![qq 20170426105349](https://cloud.githubusercontent.com/assets/5474666/25416170/f683faea-2a6e-11e7-863d-b9f0e2a24795.png)
What is the problem?

**Comment by yangzj1992** [comment]
Same to me

**Comment by ktlshya** [comment]
Same to me

**Comment by Hancoson** [comment]
ok , install a plugin,[Reactjs code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.ReactSnippets)
