### ISSUE TITLE
Spaces between css selectors

### ISSUE THREAD

**Issue by danielhammerl** [Lonefy/vscode-JS-CSS-HTML-formatter#67]
Hi guys, thats not really an issue, its more a question ( i hope its the right way to ask a question here )
How can i enable whitespaces between css selectors? So lets say my css looks like "#first-id > #second-id", the formatter makes "#first-id>#second-id". Can I change this?

**Comment by silverqx** [comment]
I have the same question, is this possible? Thank you 🙏

**Comment by silverqx** [comment]
Ok I got it, if somebody search it you have to add this to config:
```
    "css": {
        "space_around_combinator": true
    }
```

And restart `code` or `Reload window`.
