### ISSUE TITLE
Why i can't disable 'formatOnSave'!!!!!!!

### ISSUE THREAD

**Issue by liungkejin** [Lonefy/vscode-JS-CSS-HTML-formatter#69]
Why i can't disable 'formatOnSave'!!!!!!! Untill i uninstall it!!

**Comment by adrprado** [comment]
I disabled it by pressing F1 > Formatter Config:

Then edit formatter.json: modify the line "onSave" to false.

**Comment by MkLHX** [comment]
Hi there! same issue here!
The onSave: false do nothing... every edition on file format it and place the cursor at the end of file....
Very useless thing....
