### ISSUE TITLE
How to avoid line break to indent the code

### ISSUE THREAD

**Issue by GuiAlmeida** [Lonefy/vscode-JS-CSS-HTML-formatter#8]
To indent the code wanted mantesse the code in a single line without line break, setting up formatter.json.

![capturar](https://cloud.githubusercontent.com/assets/5199435/15218178/0fb66996-1835-11e6-872e-a2e9184fc06c.PNG)

**Comment by Lonefy** [comment]
@GuiAlmeida  It's a spelling mistake. Change `"selectorSeparatorNewline": false` to `"selector_separator_newline": false` in your formatter.json
![image](https://cloud.githubusercontent.com/assets/7921431/15236659/77374fda-18f9-11e6-9f1a-19a023d823e2.png)
