### ISSUE TITLE
focus position changed after press ctrl+s saving file

### ISSUE THREAD

**Issue by cenfun** [Lonefy/vscode-JS-CSS-HTML-formatter#87]
see here for detail:
https://github.com/Microsoft/vscode/issues/40684#issuecomment-353550810

I found it's caused by JS-CSS-HTML-formatter extensions, so just post new issue here.

•VSCode Version: Version 1.19.1
 Commit 0759f77
 Date 2017-12-19T09:46:23.884Z
 Shell 1.7.9
 Renderer 58.0.3029.110
Node 7.9.0
 Architecture x64
•OS Version: windows 10

Steps to Reproduce:
1.click any where in the code
2.press ctrl+s save the file
3.the focus positon changed(move to end). it should stay in the position where step 1 clicked

I can't type any next code after ctrl+s saving the file.

**Comment by Ankirama** [comment]
You can find more informations here : https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/83

**Comment by cenfun** [comment]
@Ankirama thanks, we don't use this extension anymore and replace with HookyQR/Beautify.
