### ISSUE TITLE
ES6/7 imports getting formatted 

### ISSUE THREAD

**Issue by MateuszTrN** [Lonefy/vscode-JS-CSS-HTML-formatter#9]
this ext is marvelous but I have one problem. I'm using ES6/7 syntax and when I format code all my imports are getting a bit messed up (actually they're getting cleaned up but I'd like them kept as they were).  
Example: 

`import { Some1, Some2 } from Something //this is what I want  `

is turning into:  

```
import { 
Some1, 
Some2,
} from Something  

```
which is really painful when I implement some form and use react bootstrap components because there's 5-10 elements just for this one.

**Comment by Lonefy** [comment]
I think this is a `js-beautify` issue. I'll try to find how to config `js-beautify` to make the extension format ES6/7 well.

**Comment by MateuszTrN** [comment]
as an ugly workaround when you pass the document to js-buityfy you could just skip lines if they start with "import". But if js-beautify would allow you to make it clean that would be perfect :)

**Comment by Lonefy** [comment]
@MateuszTrN Try to add `"brace_style": "collapse-preserve-inline"` in your config file.

![image](https://cloud.githubusercontent.com/assets/7921431/16444265/da5248e6-3e0f-11e6-96c9-96280dcc1a74.png)

**Comment by MateuszTrN** [comment]
Hi @Lonefy, 

Sorry for late answer. Indeed this helped. Thanks!

**Comment by gdurastanti** [comment]
This seems to still be an issue. The 'collapse-preserve-inline' param no longer disables this behavior. Uninstalled for the time being but would love a resolution.

**Comment by michele2014** [comment]
If Interested I am trying to fix the problem with a custom extension,
which relies on HookyQR.beautify-0.7.3 but it can be used also with Lonefy.
I still need to finish to test but if  you want to try you can have look [here](https://github.com/michele2014/vscode-formatter-estension)

**Comment by wf-soft** [comment]
@Lonefy This function forces the importmap to be formatted into one line, which makes it difficult to read

```
<script type="importmap">
        { "imports": { "vue": "https://unpkg.com/vue@3/dist/vue.esm-browser.js", "element-plus": "https://unpkg.com/element-plus@2.2.36/dist/index.full.mjs" } }
</script>
```
